server:
  port: 8080

spring:
  application:
    name: telecom-api

  datasource:
    url: jdbc:mysql://telecom-mysql:3306/telecom_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: change-this-development-secret-key-to-a-long-random-value